from . import barmex_account_asset
from . import barmex_account_assets_report
from . import barmex_account_bank_statement
from . import barmex_account_change_lock_date
from . import barmex_account_followup_report
from . import barmex_account_journal
from . import barmex_account_move
from . import barmex_account_move_line
from . import barmex_account_move_reversal
from . import barmex_account_payment
from . import barmex_arancel
from . import barmex_bank_office
from . import barmex_classification
from . import barmex_collector
from . import barmex_conversion
from . import barmex_corporate
from . import barmex_credit_note
from . import barmex_crm_lead
from . import barmex_customer_codes
from . import barmex_customer_product_pricelist
from . import barmex_dialog_box
from . import barmex_dialog_box_line
from . import barmex_foreign_trade
from . import barmex_foreign_trade_customs
from . import barmex_hr_employee
from . import barmex_hr_expense
from . import barmex_hr_job
from . import barmex_invoice
from . import barmex_partner_type
from . import barmex_payment
from . import barmex_petition_relation
from . import barmex_product_brand
from . import barmex_product_classification
from . import barmex_product_classification_process
from . import barmex_product_group
from . import barmex_product_pricelist
from . import barmex_product_product
from . import barmex_product_speciallity
from . import barmex_product_subgroup
from . import barmex_product_subline
from . import barmex_product_template
from . import barmex_purchase_order
from . import barmex_purchase_order_line
from . import barmex_reason
from . import barmex_res_company
from . import barmex_res_config_settings
from . import barmex_res_partner
from . import barmex_res_partner_bank
from . import barmex_res_user
from . import barmex_sale_order
from . import barmex_sale_order_line
from . import barmex_sale_zone
from . import barmex_shipping
from . import barmex_stock_landed_cost
from . import barmex_stock_move
from . import barmex_stock_move_line
from . import barmex_stock_picking
from . import barmex_stock_production_lot
from . import barmex_stock_warehouse
from . import barmex_vendor_price
from . import barmex_vendor_type
from . import barmex_writeoff_reasons
from . import barmex_crm_team
