{
    'name' : 'Barmex Golive',
    'version' : '1.3.5',
    'author' : 'Barmex',
    'website' : '',
    'category' : 'Tools',
    'sequence' : 10,
    'licence' : 'AGPL-3',
    'summary' : 'Barmex Golive',
    'depends' : ['base',
                'account',
                'account_accountant',
                'account_reports',
                'contacts',
                'crm',
                'hr',
                'hr_expense',
                'l10n_mx_edi',
                'l10n_mx',
                'mail',
                'product',
                'purchase',
                'stock',
                'sale',
                'sale_management',
                'uom',
                'account_debit_note'],
    'data' : [
        #security
        'security/model_security.xml',
        'security/ir.model.access.csv',
        #views
        'views/res_partner.xml',
        'views/account_bank_statement.xml',
        'views/golive_account_bank.xml',
        'views/purchase_order_search.xml',
    ],
    'installable' : True,
    'application' : True,
    'auto_install' : False,
}
