{
    'name' : 'Barmex',
    'version' : '1.3.5',
    'author' : 'Barmex',
    'website' : '',
    'category' : 'Tools',
    'sequence' : 10,
    'licence' : 'AGPL-3',
    'summary' : 'Barmex customization modules',
    'depends' : ['base','account','account_accountant','account_reports','account_followup', 'contacts','crm','hr',
                 'hr_expense','l10n_mx_edi','l10n_mx','mail','product','purchase','stock','sale',
                 'sale_management','uom', 'account_debit_note'],
    'data' : [
        #wizards
        'wizards/barmex_account_journal_wizard.xml',
        'wizards/barmex_alert.xml',
        'wizards/barmex_cfdi_relacionado.xml',
        'wizards/barmex_account_invoice_send_form.xml',
        'wizards/barmex_mail_compose_message.xml',
        'wizards/barmex_move_products.xml',
        #data
        'data/barmex_mail_invoice_template.xml',
        'data/barmex_mail_data.xml',
        'data/barmex_reason.xml',
        'data/ir_module_category_data.xml',
        #security
        'security/barmex_res_partner.xml',
        'security/company_filters.xml',
        'security/barmex_account_security.xml',
        'security/barmex_model_security.xml',
        'security/ir.model.access.csv',
        #actions
        'views/barmex_server_action.xml',
        'views/barmex_automated_actions.xml',
        #views
        'views/barmex_account_asset.xml',
        'views/barmex_account_bank_statement.xml',
        'views/barmex_account_change_lock_date.xml',
        'views/barmex_account_journal.xml',
        'views/barmex_account_move.xml',
        'views/barmex_account_move_debit_view.xml',
        'views/barmex_account_move_reversal.xml',
        'views/barmex_account_payment.xml',
        'views/barmex_classification.xml',
        'views/barmex_conversion.xml',
        'views/barmex_credit_note.xml',
        'views/barmex_crm_lead.xml',
        'views/barmex_dialog_box.xml',
        'views/barmex_foreign_trade.xml',
        'views/barmex_foreign_trade_customs.xml',
        'views/barmex_hr_employee.xml',
        'views/barmex_hr_expense.xml',
        'views/barmex_hr_job.xml',
        'views/barmex_invoice.xml',
        'views/barmex_partner_type.xml',
        'views/barmex_payment.xml',
        'views/barmex_petition_relation.xml',
        'views/barmex_product_brand.xml',
        'views/barmex_product_category.xml',
        'views/barmex_product_classification.xml',
        'views/barmex_product_classification_process.xml',
        'views/barmex_product_group.xml',
        'views/barmex_product_pricelist.xml',
        'views/barmex_product_product.xml',
        'views/barmex_product_speciallity.xml',
        'views/barmex_product_subgroup.xml',
        'views/barmex_product_subline.xml',
        'views/barmex_product_template.xml',
        'views/barmex_purchase_order.xml',
        'views/barmex_reason.xml',
        'views/barmex_res_config_settings.xml',
        'views/barmex_res_partner.xml',
        'views/barmex_res_partner_custom.xml',
        'views/barmex_res_user.xml',
        'views/barmex_sale_order.xml',
        'views/barmex_sale_zone.xml',
        'views/barmex_stock_landed_cost_custom.xml',
        'views/barmex_stock_move.xml',
        'views/barmex_stock_picking.xml',
        'views/barmex_stock_production_lot.xml',
        'views/barmex_stock_quant.xml',
        'views/barmex_stock_warehouse.xml',
        'views/barmex_vendor_type.xml',
        'views/barmex_writeoff_reasons.xml',
        'views/barmex_product_template_product_form.xml',
        #'views/website_homepage1.xml',
        #wizards
        'wizards/barmex_account_journal_wizard.xml',
        'wizards/barmex_alert.xml',
        #reports
        'reports/barmex_cost_effectiveness.xml',
        'reports/barmex_cost_effectiveness_template.xml',
        'reports/barmex_customer_aging.xml',
        'reports/barmex_customer_aging_template.xml',
        'reports/barmex_account_journal_template.xml',
        'reports/barmex_account_journal_report.xml',
        'reports/barmex_sale_template.xml',
        'reports/barmex_invoice_template.xml',
        'reports/barmex_invoice_report.xml',
        'reports/barmex_base_templates.xml',
        'reports/barmex_delivery_templates.xml',
        'reports/barmex_reception_template.xml',
        'reports/barmex_requisition_template.xml',
        'reports/barmex_transfer_template.xml',
        'reports/barmex_inventory_template.xml',
        'reports/barmex_account_payment_report.xml',
        'reports/barmex_note_cargo_template.xml',
        'reports/barmex_reports.xml',
        #menu
        'views/barmex_action.xml',
        'views/barmex_menu.xml',
        #addenda
        'addendas/barmex_addenda.xml',
        'addendas/calsonickansei.xml',
        'addendas/del_valle.xml',
        'addendas/envases.xml',
        'addendas/femsa.xml',
        'addendas/hornos.xml',
        'addendas/lala.xml',
        'addendas/mabe.xml',
        'addendas/minera.xml',
        'addendas/pemex.xml',
        'addendas/pilgrims.xml',
        'addendas/porcelanite.xml',
        'addendas/sabritas.xml',
        'addendas/sanmina.xml',
        'addendas/sergoba.xml',
        'addendas/zf.xml',
    ],
    'installable' : True,
    'application' : True,
    'auto_install' : False,
}
